name: amr-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - streamlit
  - scikit-learn
  - pandas
  - joblib
  - biopython
  - matplotlib
  - abricate
  - pip
  - flake8
  - pip:
      - click        # if you later add a CLI
      - pytest       # for tests
